### ISSUE TITLE
Improvements to Red Queen

### ISSUE THREAD

**Issue by mtreinish** [qiskit-advocate/qamp-fall-22#30]
### Description

Red Queen, https://github.com/Qiskit/red-queen, is a quantum compiler benchmark framework that we're using in Qiskit to characterize the performance (both runtime and quality) of qiskit's compiler (i.e. `transpile()`)

### Deliverables

The project is to work on improving the red queen framework. The primary deliverables will be pull requests to the project adding new benchmarks and making general improvements to the framework.

### Mentors details

- Mentor 1
    - Name: Matthew Treinish
    - GitHub ID: @mtreinish
    - What they do: Qiskit Core Developer

### Number of mentees

3

### Type of mentees

- Mentee 1
  - Required:
    - Python programming
  - Nice to have:
    - Experience with software benchmarking
    - Experience with PyTest

**Comment by gideonuchehara** [comment]
Hello @mtreinish , I am interested in this project. I have submitted my application for mentorship. Please, let me know what the next steps are. Looking forward to working with you. Thanks.

**Comment by archanaravindar** [comment]
Hi @mtreinish This project interests me as it overlaps with both areas I have worked earlier- compiler performance and development. I have submitted my application for the QAMP fall program. if there is a spot for a mentee available I m interested.

**Comment by shraddha-aangiras** [comment]
@GemmaDawson

**Comment by archanaravindar** [comment]
Uploading checkpoint 1 presentation @GemmaDawson 
[qamp-proposal.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9735503/qamp-proposal.pptx)
[Uploading qamp-proposal.pptx…]()

**Comment by GemmaDawson** [comment]
@archanaravindar - please review that upload.  It is not correct

**Comment by archanaravindar** [comment]
Thanks for noticing! uploaded the correct file @GemmaDawson

**Comment by archanaravindar** [comment]
Checkpoint2: 

Progress so far on integrating MQTbench to red queen 
Picked Amplitude estimation test as a proof of concept test and was able to create similar test files using red queen framework and run the test 
Simplifications assumed: circuit created in .qasm, no fidelity comparisons 
![4B45340D-0405-4E48-9796-A5D4AC6B6F71](https://user-images.githubusercontent.com/13232668/199208711-2a7e3ebc-714d-4752-8d93-85b8ffaf2d39.jpeg)
![3DE4A19E-BB19-4B19-A66B-A0D733F2A3F2](https://user-images.githubusercontent.com/13232668/199208724-a3871cca-747b-49ce-a6f5-69438f47df73.jpeg)

Updated .py file to create circuit and run it in memory instead of putting it into a qasm file 

Next steps: 

1. To discuss about fidelity comparisons and mid-circuit measurements with Matthew 

@GemmaDawson @mtreinish

**Comment by archanaravindar** [comment]
Added most benchmarks from MQTBench to red queen here https://github.com/Qiskit/red-queen/pull/48/ 
Currently testing and working on visualisation of results

**Comment by archanaravindar** [comment]
Presentation for final checkpoint is attached. 
[finaldemo-qamp-fall-2022-archana.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10268138/finaldemo-qamp-fall-2022-archana.pdf)

detailed results here : https://ibm.box.com/s/6xkaof9ntcf96bl7wmpsk2zw6btfpn23

**Comment by GemmaDawson** [comment]
@archanaravindar - this link is not correct, please update it

**Comment by archanaravindar** [comment]
> @archanaravindar - this link is not correct, please update it

is it ok now @GemmaDawson

**Comment by GemmaDawson** [comment]
It is!  Thank you @archanaravindar!

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟

**Comment by shraddha-aangiras** [comment]
Presentation for final checkpoint
https://slides.com/shraddhashankaraangiras/improvements-to-red-queen
