### ISSUE TITLE
Variational quantum linear solver for multiphysics

### ISSUE THREAD

**Issue by ljubabu** [qiskit-advocate/qamp-fall-22#31]
### Description

Application of the Variational Quantum Linear Solver (VQLS) for solving Multiphysics problems is investigated. To solve Multiphysics problems like heat transport, fluid flow, etc., the corresponding differential equations describing the physical process are first discretized in order to obtain corresponding system of algebraic equations and then solved by applying the VQLS. Since this methodology often produces matrices having a complex structure (in comparing to the simple cases from the literature), this research will be focused on finding the optimal ansatz as well on solving the arbitrary matrix input problem.  For this purpose Qiskit simulators as well as real devices will be utilized.  

### Deliverables

Solution of the system of linear equations describing some simple Multiphysics problem by using the VQLS method. 

### Mentors details

- Mentor 1
  - Name: Budinski Ljubomir
  - GitHub ID: https://github.com/ljubabu
  - What they do: Quantum Algorithm Researcher at [Quanscient](https://quanscient.com/team/) and Qiskit advocate

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Knowledge of linear algebra and Variational Quantum Linear Solver
    - Proficient in Qiskit

**Comment by ssawarn** [comment]
this seems a promising topic to work on. Can you refer to some references for more details so that I get to decide whether to opt this particular problems or not?

**Comment by ljubabu** [comment]
@stoicodin Thanks for your interest in this project. Here is the paper which is planned to  be used as the reference for this project. [2022-Application of a variational hybrid quantum-classical algorithm to heat conduction equation.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9400903/2022-Application.of.a.variational.hybrid.quantum-classical.algorithm.to.heat.conduction.equation.pdf)

**Comment by Hirmay** [comment]
Hi @ljubabu, this project looks quite interesting to me. I have some knowledge and experience of VQE. I would love to contribute to this project.

Edit: I have gone through the entire paper mentioned and understood most aspects of the paper. I'm pretty intrigued by the project and am interested in working on this project.

**Comment by Qcatty** [comment]
Hi, i would like to join this project, i have already worked on L-VQE, F-VQE(on  VRP) and DA-VQE, i would like to to use VQLS to solve heat conduction equation,

**Comment by ljubabu** [comment]
Hi @Hirmay  and @echchallaouy  . Very sorry for late response. Thank you very much for your interest in this project . I will make the selection as soon as possible.

**Comment by smendoncabruna** [comment]
Hi @ljubabu , I am very interested in this project! 
Will you inform about your decision regarding this project through here?

**Comment by Mostafa-Atallah2020** [comment]
@GemmaDawson

**Comment by Mostafa-Atallah2020** [comment]
# Checkpoint 1

The link to the presentation slides 

https://slides.com/mostafaataallah/solving-multiphysics-problems-on-quantum-computers

**Comment by Mostafa-Atallah2020** [comment]
![1](https://user-images.githubusercontent.com/67621237/194590070-cf207289-33e9-4b15-a855-b2f345acd8c7.png)
![2](https://user-images.githubusercontent.com/67621237/194590077-7e67db3e-947c-4595-a221-ebc305a58676.png)
![3](https://user-images.githubusercontent.com/67621237/194590080-9892c611-7eac-4e93-a3a5-ce7a44db87b5.png)
![4](https://user-images.githubusercontent.com/67621237/194590084-a5fb24f4-6098-47c2-966f-e97d789d1c7a.png)
![5](https://user-images.githubusercontent.com/67621237/194590086-dad34cdc-3748-4cf4-92a5-2f197235687f.png)
![6](https://user-images.githubusercontent.com/67621237/194590090-f1408f34-e49f-4391-9a04-847532aa0b34.png)

**Comment by Mostafa-Atallah2020** [comment]
# Checkpoint 2

## Finished work 

We solved the one-dimensional heat equation in [1] using the Variational Quantum Linear Slover (VQLS) with qiskit. We used the global cost function approach defined in [2]. We improved the overlap between the output solution and the exact solution from 0.737 on a simulator to 0.999 on a simulator and 0.868 on a noisy simulator by choosing the Classical Optimizer Constrained Optimization By Linear Approximation optimizer (QOBYLA). We proved that the solution fidelity does not depend on the circuit depth but rather on the appropriate choice of the classical optimizer.

### Global Cost Function Circuits

![had_test_global](https://user-images.githubusercontent.com/67621237/199747722-6364ff7a-5567-4eaa-a375-197153a02f5d.png)

![special_had_test_global](https://user-images.githubusercontent.com/67621237/199747728-51739155-1fbf-4cb2-990b-89b4163dc3cd.png)

### Local Cost Function Circuits

![had_test_local](https://user-images.githubusercontent.com/67621237/199747734-04276e6b-dfa3-4bef-94b9-71672b6c9008.png)

## Ongoing work

We simulate the results on real IBMQ hardware. Due to a large number of circuit iterations. The time of running a 3 by 3 matrix problem has been estimated to be about 150 hours. So, we employ qiskit runtime to reduce that time as possible. Also, we implement the local cost function approach in [2] because it has fewer gates and which reduces the circuit noise and hence improves the fidelity. Lastly, we study quantum chip qubits connectivity and use the error mitigation techniques which can significantly improve expectation values and therefore the final fidelity.

References 
1. https://arxiv.org/abs/2207.14630
2. https://arxiv.org/abs/1909.05820

**Comment by Mostafa-Atallah2020** [comment]
# Final Showcase

The link to the presentation slides

https://slides.com/mostafaataallah/solving-multiphysics-problems-on-quantum-computers-1e46dd

**Comment by Mostafa-Atallah2020** [comment]
![1](https://user-images.githubusercontent.com/67621237/206743275-b96681b6-bb26-486b-bd27-ecb6e30c44ef.jpg)
![2](https://user-images.githubusercontent.com/67621237/206743296-011abf11-7350-423c-9ba9-16327085af62.jpg)
![3](https://user-images.githubusercontent.com/67621237/206743304-d136d291-5adb-4f86-8f09-4cd50591f4f6.jpg)
![4](https://user-images.githubusercontent.com/67621237/206743319-b96befd6-287f-4a80-9c22-4f4affabe165.jpg)
![5](https://user-images.githubusercontent.com/67621237/206743331-4f85a375-8654-44b8-a947-d43434418835.jpg)
![6](https://user-images.githubusercontent.com/67621237/206743342-bd687596-645a-4f72-aaee-fb42a4392c7a.jpg)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
