### ISSUE TITLE
Quantum open systems and master equation implementation through reinforcement learning

### ISSUE THREAD

**Issue by amitracal** [qiskit-advocate/qamp-fall-22#35]
### Description

The quantum open systems master equation has the Schrodinger portion of the equation plus the non-unitary thermal dissipation part. The objective here is to come up with an implementation where the Schrodinger part is solved unitary operations but the other piece is learnt through an agent acting in the open environment through reinforcement learning or RL.

### Deliverables

A good presentation
possible patent
possible paper

### Mentors details

- Mentor 1
  - Name:
  - GitHub ID:
  - What they do:
- Mentor 2
  - Name:
  - GitHub ID:
  - What they do:

Mentor needed

### Number of mentees

3

### Type of mentees

- Mentee 1
  - Required:
    - item 1
  - Nice to have:
    - item 1
- Mentee 2
  - Required:
    - item 1
  - Nice to have:
    - item 1

Abhijit Mitra 
amitracal
Alberto Maldonado
MaldoAlberto
Vaibhaw Kumar
vkkumar19

**Comment by hykavitha** [comment]
Hi @amitracal I would like to contribute. @hykavitha

**Comment by amitracal** [comment]
Mentor - Abhijit Mitra
@amitracal 

Mentee - Alberto Maldonado
@maldoalberto

Vaibhaw Kuma
@vkkumar19

Kavitha Yograj
@hykavitha 

@HuangJunye - please note this

**Comment by Hirmay** [comment]
HI @amitracal, the problem seems quite interesting. I would love to contribute!

**Comment by HuangJunye** [comment]
@amitracal Will you be the mentor for this project or are you looking for a mentor?

**Comment by Gaya3-mv** [comment]
Hi @amitracal, this looks like an interesting research problem. I would also like to be a part of it.

**Comment by amitracal** [comment]
> @amitracal Will you be the mentor for this project or are you looking for a mentor?

@HuangJunye I will be the mentor

**Comment by amitracal** [comment]
> Gaya3-mv

Will be happy to take you in.

**Comment by ssawarn** [comment]
are there more positions open for this project? This seems a promising field to explore

**Comment by Gaya3-mv** [comment]
> > Gaya3-mv
> 
> Will be happy to take you in.

Thank you @amitracal. That would be great.

**Comment by KakashiOO7** [comment]
Hi @amitracal ,
It's looks quite interesting to I would be lucky to collaborate on this with you.
Hoping to hear from you soon.

Thank you

**Comment by amitracal** [comment]
@HuangJunye What is the limit of the number of people we can get in one team - We have Alberto, Vaibhaw, Kavitha & Gayathree plus me as mentor but there is two more requests so was wondering, will be happy to take them but do not want to cross the limits.

**Comment by Hirmay** [comment]
Hello @amitracal, I also applied at the start of the thread, but it seems like my message got crowded up and was not seen by you 😅.

**Comment by amitracal** [comment]
I see, sorry about that. I will wait for Junye's advice on the size of the cohort before any expansion beyond first 4 mentees.

**Comment by Hirmay** [comment]
No need, I understand!

**Comment by HuangJunye** [comment]
@amitracal I would advise to take only 3 mentees as this is the first time you become a mentor. We have a mentor training session today. Let me add you.

**Comment by amitracal** [comment]
@HuangJunye I hear you. I will definitely not expand beyond 4, let me talk a few individually and see we can shorten it to three.

**Comment by ssawarn** [comment]
I want to work on it @amitracal

**Comment by MaldoAlberto** [comment]
@GemmaDawson

**Comment by Gaya3-mv** [comment]
Checkpoint 1 presentation for #35

[pjt _35_ppt_QAMP.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9731281/pjt._35_ppt_QAMP.pptx)

**Comment by Gaya3-mv** [comment]
Checkpoint 1 presentation for project #35

[pjt _35_ppt_QAMP.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9736341/pjt._35_ppt_QAMP.pdf)

**Comment by Gaya3-mv** [comment]
## Checkpoint 2:
### Project #35
In this project, we aim to study the evolution of an open quantum system using reinforcement learning (RL) for the non-unitary part. As a first step towards working with RL on an environment involving a quantum circuit, we are trying to reproduce the results of a study [^1] done to perform quantum error correction using RL techniques. Here, we are using a Qiskit QuantumCircuit object, with the gate sequences on it being optimized by RL. For the first checkpoint, we were learning simple use cases of RL and of creating custom environments.

Our progress so far:

- We created a custom environment involving a quantum circuit. The episode length is defined to be the maximum number of gate operations that can be performed on the circuit. Here, the RL agent is to be trained to get the best sequence of gates on an initial quantum state to achieve the target state that we want.

   - The action space: The gate operations that can be performed on the circuit in accordance with the basis gate set chosen. It also includes the `no gate operation' as an action, so that if the agent learns to create the target state in fewer steps than that defined by default, it will stop the gate operations there so that the achieved state does not get destroyed.
        
   - The observation space: An array of size $1 \times 2^n$ to store the state vector of the $n$ qubit system after each step. 
        
   - Reward: The reward is based on the fidelity between the intermediate state (after a gate operation) and the required target state. The reward progressively increases as 1, 10, and 100 for the ranges of fidelities $(0.5, 0.9), [0.9, 0.99),$ and $[0.99, 1.0],$ respectively. For all other non-optimal values of the fidelity, the reward is set to $-1$.
  
   The training was done using the Proximal Policy Optimization (PPO) algorithm.
- The above approach was first tried on a two-qubit example and a Bell state was successfully learnt by the agent. In this example, the basis gate set comprised the $H$, $T$, and $CX$ gates on the circuit with two qubits. Later, it was extended to a general $n$ qubit case with the $H$ and $CX$ gates as the actions on a circuit starting in the all-zero state and having the GHZ state (for the $n$ qubit system) as the target state.    
- We are also learning and understanding the open system evolution dynamics, which is progressing parallel to the coding work.

The upcoming tasks we have envisaged are:

- [ ] Using a Recurrent Neural Network (RNN) to learn to choose the best circuit (having maximum fidelity and minimal cost) from the ones learnt by the RL agent. 
    
- [ ] To use a similar approach to do the training on density matrices (instead of on the state vectors used here), since the evolution of an open quantum system has non-unitary parts (hence leading to non-unitary actions also in the environment), which can be described only using a density matrix framework.
    
- [ ] Studying the different RL algorithms available and making an effective comparison of these to choose the best one suitable for our objective.

<picture>
 <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/86402649/199663114-854f1013-4e70-4cb2-951c-489fd1848eb0.JPG">
 <source media="(prefers-color-scheme: light)"srcset="https://user-images.githubusercontent.com/86402649/199663161-b4debe33-1f4d-4b70-9cbe-0f15e54ec06f.JPG">
 <img alt="final learnt circuit sequences" src="https://user-images.githubusercontent.com/86402649/199663190-7b1030c2-0dce-422f-9c9a-64e4725a64c6.JPG">
</picture>

*Figure (a) above shows the final gate sequence learnt by the agent for creating the Bell state* $(|00\rangle + |11\rangle)/\sqrt 2$ *from the initial* $|00\rangle$ *state. 
Similarly, figure (b) shows the output from the program for the general case of creating the GHZ state for any number of qubits, starting from the all-zero state. Here, the example is for creating the* $(|000\rangle + |111\rangle)/\sqrt 2$.
*In both cases, we can see that the gate sequence stops appropriately once the fidelity is maximum, irrespective of the gate sequence length set by default.*
[^1]: T. Fösel, P. Tighineanu, T. Weiss, F. Marquardt, Reinforcement learning with neural networks for quantum feedback. Phys. Rev. X 8(3), 031084 (2018). https://doi.org/10.1103/physrevx.8.031084

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by Gaya3-mv** [comment]
Final checkpoint presentation for project #35
[pjt _35_final_checkpoint_QAMP.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10220879/pjt._35_final_checkpoint_QAMP.pdf)

**Comment by ssawarn** [comment]
Final checkpoint material #35
Theory : [qamp#35.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10226034/qamp.35.pdf)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟

**Comment by amitracal** [comment]
@KakashiOO7 and @Hirmay - Although QAMP Fall22 has ended a few of us continue to work on this problem, do you want to join us ? If so please @amitracal know

**Comment by Hirmay** [comment]
Yes, I'm interested in working on this problem!

**Comment by amitracal** [comment]
Awesome, can u please send a slack message to me (Abhijit Mitra)Sent from my iPhoneOn Dec 24, 2022, at 3:48 AM, Hirmay Sandesara ***@***.***> wrote:﻿
Yes, I'm interested in working on this problem!
