### ISSUE TITLE
Quantum Fractal Art for Educational Purposes and Exhibitions

### ISSUE THREAD

**Issue by JRussellHuffman** [qiskit-advocate/qamp-fall-22#38]
### Description

Fractals have the potential to be an exciting way to visualize quantum information that bridges art, science, and nature. Building upon previous work https://github.com/wmazin/Visualizing-Quantum-Computing-using-fractals the intent is to 
Create fractal presentations of common 1- and 2-qubit gates and circuits: this could, for example, be by creating a sensible 1-1 mapping of what key quantum gates e.g. Hadamard gate, look like or by creating a sensible mapping of what the gate operations look like when acted on quantum states. In this second case, we could use colour or shapes to represent gate operations on before / after images of the quantum states. 
Prepare the fractals for an art exhibition, either online or pen plotted versions

The hope and ambition is that this PoC project may be the beginning of developing an educational kit (app?) or Qiskit Textbook module for non-technical audiences leveraging the beauty and fascination of fractals. 
Further work is needed to mature this idea. Open to suggestions.

### Deliverables

At least 5 fractal images of common 1- and 2-qubit gates and circuits. 
Identification of at least one art exhibition that has expressed interest in displaying the quantum gate fractals

### Mentors details

Name: Russell Huffman
GitHub ID: [@JRussellHuffman](https://github.com/JRussellHuffman)
What they do: Qiskit Design Lead

### Number of mentees

2

### Type of mentees

Mentee 1 
Required: Background and experience with chaos theory and fractals. Interested in generative art with Qiskit and how to convey quantum to non-technical audience.

Mentee  2
Required: Deep physics background with interest in learning / working with fractals and developing  content that can help to make quantum more accessible to wider audiences.

**Comment by Morcu** [comment]
Hi. I'm interested in the project, I have messaged you in slack :)

**Comment by alejandrogm668** [comment]
Looks great! I have also messaged you in slack :nerd_face:

**Comment by ShivaniRajput11** [comment]
Hi @JRussellHuffman I am interested to work on this project.

**Comment by kvcmarshall6** [comment]
@GemmaDawson - for assigning this project please add myself, Wiktor Mazin and @Morcu!

**Comment by wmazin** [comment]
@GemmaDawson

**Comment by wmazin** [comment]
Checkpoint 1

[Checkpoint 1 - QAMP Fall 2022 - #38 Quantum Fractal Art for Educational Purposes and Exhibitions - October 2022.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9730542/Checkpoint.1.-.QAMP.Fall.2022.-.38.Quantum.Fractal.Art.for.Educational.Purposes.and.Exhibitions.-.October.2022.pdf)

**Comment by kvcmarshall6** [comment]
**Checkpoint 2 Update**

Since Checkpoint 1, the team has worked together to build various visual representations of quantum circuits and quantum states, as well as think about how and where to display our outputs. Our key areas of focus have included:

- Exploring how to display our fractal representations e.g. at a children’ science exhibition:
Our team held a brainstorming workshop to decide the best way to display the fractal images and animations at an exhibit built for children, with the aim of offering an alternative, visual way to understand quantum states and circuits. In this workshop, we decided on a station-style exhibit where a user could interact with a one-qubit fractal representation of a state using a keypad and interactive mouse, to see how their movements impacts the state. 

<img width="185" alt="image" src="https://user-images.githubusercontent.com/35499788/199483652-320d33da-dee6-4469-a588-82ce5de2419e.png">

<img width="333" alt="image" src="https://user-images.githubusercontent.com/35499788/199483679-0afc8aea-72d5-4898-85ae-03166d507f6d.png">

- Contacting art / science exhibitions for displaying our work:
Our team mentor, Russell Huffman, is hoping to host his own exhibition next year where artefacts such as those we produce as part of this project could be displayed. Our team are also reaching out to possible external exhibitors in our geographies.

In terms of our more technical tasks, we have continued to work on the following areas:

- Building 3-dimensional images of single qubit gates: 
With our catalogue of single qubit gate fractal representations, we wanted to make these images more visually exciting by building layered 2D and 3D representations of the single qubit gate actions. This first created overlayed images of a single qubit gates at various degrees of rotation using Adobe photoshop. 

<img width="185" alt="image" src="https://user-images.githubusercontent.com/35499788/199483941-c3833d79-6fee-4dfa-8a95-a6b6f5d926d5.png"> Z-Rotations: with 4 overlayed images.

We also explored creating 3D models using Blender. We tried using vectorised versions of the layered 2D images produced in Adobe photoshop as well as building 3D “MRI-style” models of various degrees of rotation of the single qubit gates.  

<img width="311" alt="image" src="https://user-images.githubusercontent.com/35499788/199484146-8773edbe-9c00-48ec-94a1-ec1e5e0f9c71.png">

- More progress in >1 qubit gate images and animations:
The team has explored more complex qubit images and animations for common circuits and state preparations – using various preparations of the complex number used in Julia set matings, and different formulations of the rational functions. 
An example animation of a 6-qubit GHZ state is shown below:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/35499788/199484251-59d69079-366c-46d8-bcc6-ce2468f5e4b2.png">

- Producing higher quality fractal images:
This goal became urgent when the team discussed presenting our work at a children’s science/art exhibit. We managed to create higher quality images of existing fractals using PyMandel, Blender and p5.js, e.g.:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/35499788/199484419-129b165e-8af4-45ca-989a-861feb515ee2.png">

- Teleportation protocol with 3-qubit fractal images:
We explored how to visualise the teleportation protocol using 2 different formulations of Julia sets. We opted to take snapshots of the 3-qubit fractal at different stages of the teleportation process, as is demonstrated below. The team are also interested in building an animation for the protocol. 

To see the teleportation story through fractals, see attached document in next comment:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/35499788/199484575-c4a80974-114c-4cfc-94eb-7239f7ea1cd5.png">

**Comment by kvcmarshall6** [comment]
For some of the media to be seen correctly please open the attached Word doc: 
[Checkpoint 2.docx](https://github.com/qiskit-advocate/qamp-fall-22/files/9920102/Checkpoint.2.docx)

**Comment by kvcmarshall6** [comment]
Our visual representation of our project so far is seen below!

<img width="333" alt="image" src="https://user-images.githubusercontent.com/35499788/199485006-8653388b-fdb6-43c1-ab2e-34034f6a07f7.png">

<img width="315" alt="image" src="https://user-images.githubusercontent.com/35499788/199484981-9cc9a85c-2db8-4076-84f3-b4b9022b4942.png">

**Comment by wmazin** [comment]
Our final showcase Dec 8
[Final Showcase - QAMP Fall 2022 - #38 Quantum Fractal Art for Educational Purposes and Exhibitions - December 2022.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10184074/Final.Showcase.-.QAMP.Fall.2022.-.38.Quantum.Fractal.Art.for.Educational.Purposes.and.Exhibitions.-.December.2022.pdf)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
